name: Unit tests

# Controls when the action will run.
on:
  # Triggers the workflow on push or by cron schedule
  push:
    branches:
      -  '*'    # push to any branch
  pull_request:
  schedule:
    - cron: "0 13 * * 1" # Every Monday at 1PM UTC (9AM EST)

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  unittest:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['7.2', '7.3', '7.4', '8.0']
    name: Unittest on ${{ matrix.operating-system }} with PHP version ${{ matrix.php-versions }}
    steps:
    - name: Set up MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        mysql version: '5.7'
        mysql root password: 'testMySQLPassword123'

    - name: Checkout from GIT
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: mbstring, mysqli, intl, curl #optional, setup extensions
        coverage: xdebug #optional, setup coverage driver

    - name: Check PHP Version
      run: php -v

    - name: Composer install
      run: |
        composer install

    - name: Install WP Tests
      run: bash bin/install-wp-tests.sh wordpress_test root 'testMySQLPassword123' 172.17.0.1 latest

    - name: Run unit tests
      run: |
        mkdir -p build/logs
        ./vendor/bin/phpunit --fail-on-warning --fail-on-risky --disallow-test-output --coverage-clover build/logs/clover.xml

    - name: Upload coverage results to coveralls.io
      if: matrix.php-versions == '7.2'
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        vendor/bin/php-coveralls --coverage_clover=build/logs/clover.xml -v

    - name: Smoke tests phpstan and PHP-Compability (using phpcs) with PHP ${{ matrix.php-versions }}
      if: matrix.php-versions == '7.2'
      run: |
        composer update phpstan/phpstan --ignore-platform-reqs
        vendor/bin/phpcs --config-set installed_paths vendor/phpcompatibility/php-compatibility
        vendor/bin/phpcs -p . --standard=PHPCompatibility --runtime-set testVersion 7.0 --ignore="vendor,*.js,*.min.css"
        vendor/bin/phpstan analyse . -c phpstan.neon
