name: Release

# Controls when the action will run.
on:
  push:
    # Pattern matched against refs/tags
    tags:
    - 'v*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    strategy:
      matrix:
        include:
          - environment: testing
          - environment: production
    environment:
      name: ${{ matrix.environment }}

    runs-on: ubuntu-latest
    name: Deployment to WP SVN (tag only)
    steps:
    - name: Checkout from GIT
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.3
        extensions: mbstring, mysqli, intl, curl #optional, setup extensions

    - name: Check PHP Version
      run: php -v
    - name: Set env tag value
      run: echo "TRAVIS_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: composer install
      run: composer install
    - name: Build release
      run: make release
    - name: Run svn commit script
      run: |
        echo $TRAVIS_TAG
        sh bin/commit-svn $TRAVIS_TAG --stable > /dev/null
      env:
        SVNURL: ${{ secrets.SVNURL }}
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USER: ${{ secrets.SVN_USER }}
        TRAVIS_TAG: ${{ env.TRAVIS_TAG }}
